//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace books.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class livres
    {
        public int Id { get; set; }
        public string img { get; set; }
        public string titre { get; set; }
        public Nullable<double> prix { get; set; }
        public Nullable<int> quantite { get; set; }
        public string categorie { get; set; }
    }
}
