//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace books.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class panier
    {
        public int Id { get; set; }
        public string nomcl { get; set; }
        public Nullable<float> prixtotal { get; set; }
    }
}
